#!/bin/bash
CONF=/etc/udp-zipvpn/telegram.conf
TOKEN=$(grep BOT_TOKEN $CONF | cut -d= -f2)
CHAT=$(grep CHAT_ID $CONF | cut -d= -f2)

curl -s -X POST https://api.telegram.org/bot$TOKEN/sendMessage -d chat_id="$CHAT" -d text="$1" >/dev/null
